# dense:
#   layers:
#     - 1
#     - 3
#   units:
#     - 4
#     - 64
#   dropout:
#     - 0.0
#     - 0.5
#   batch_size:
#     - 16
#     - 128
#   lr:
#     - 0.0001
#     - 0.01
#   type: pytorch

# lstm:
#   layers:
#     - 1
#     - 3
#   units:
#     - 4
#     - 64
#   dropout:
#     - 0.0
#     - 0.5
#   batch_size:
#     - 16
#     - 128
#   lr:
#     - 0.0001
#     - 0.01
#   type: pytorch

linear:
  type: sklearn

knn:
  n_neighbors:
    - 2
    - 32

  type: sklearn

decisiontree:
  max_depth:
    - 2
    - 32
  type: sklearn

lasso:
  regularization:
    - 0.
    - 1.
  type: sklearn

rf:
  max_depth:
    - 3
    - 64
  n_estimators:
    - 2
    - 100
  min_samples_split:
    - 2
    - 256
  type: sklearn

xgb:
  max_depth:
    - 3
    - 64
  n_estimators:
    - 2
    - 100
  eta:
    - 0
    - 1
  min_child_weight:
    - 2
    - 256
  type: sklearn

catboost:
  depth:
    - 3
    - 64
  iterations:
    - 2
    - 100
  learning_rate:
    - 0
    - 1
  min_child_samples:
    - 2
    - 256
  type: sklearn


lightgbm:
  max_depth:
    - 3
    - 64
  num_iterations:
    - 2
    - 100
  learning_rate:
    - 0
    - 1
  min_data_in_leaf:
    - 2
    - 256
  early_stopping_round: 10
  type: sklearn
